# Background

Social determinants of health encompass a wide range of social, economic, and environmental factors that influence health outcomes across an individual’s lifespan. These include conditions related to birth, early development, living environment, education, employment, and aging, along with access to financial resources, political power, and social support systems. SDOH studies are very common in the field of public health. Often these studies are performed by leveraging publicly available data or by survey sampling. Most studies look at particular social determinants and utilize descriptive statistics and basic modeling for analysis. 

California healthcare spending is estimated at around $400 billion annually, with Medi-Cal being an estimated $160 billion of it. [] With the cost of healthcare rising every year, many California residents are unable to keep up. Hospitalizations in particular constitute a substantial portion of healthcare spending, with many being preventable. This project builds on to the traditional SDOH study by employing advanced machine learning techniques to investigate the associations between social determinants of health and preventable hospitalization rates at the county level within California. The analysis identifies underlying patterns both within individual counties and between different counties, offering insights into the broader structural and regional dynamics that contribute to disparities in preventable hospitalizations.

Five social determinants of health were chosen for analysis across 58 counties in California: Population, Education, Unemployment, Type of Employment, and Racial demographics. Population was chosen due to the varying size of counties, some being more rural and some having metropolitan centers. Education, Race, and Unemployment were chosen due to the extensive studies done that show that they have direct impacts on health. [] Type of Employment was included as it reflects not only socioeconomic status but may be a reflection of the demographics of a county.