
project:
  type: manuscript
  output-dir: docs

manuscript:
  article: Capstone_Rough.qmd

format:
  html:
    theme: cerulean
    toc: true
    toc-location: left
    number-sections: false
    title-block-banner: true